{"pages" :[

{	"id": "3226114141",
    "location": "Sunrise over Daytona Beach, FL",
    "source": "reddit",
    "source_link": "http://www.reddit.com/r/EarthPorn/comments/1q8gbf/sunrise_over_daytona_beach_fl_5184x3456/",
    "image_link": "http://farm3.staticflickr.com/2832/10702606596_9f38532eb9_b.jpg",
    "lat_long": ["29.2000", "81.0333"],
    "weather_link": "http://weather.yahoo.com/united-states/florida/daytona-beach-2389922/#toggle",
    "weather_current_type": "mostly cloudly",
    "weather_current_now": 26,
    "weather_today_high": 26,
    "weather_today_low": 18,
    "nearby_place1_name": "Daytona Beach",
    "nearby_place1_url": "https://foursquare.com/v/daytona-beach/4bf818728d30d13a6e180018",
    "nearby_place2_name": "Bjs Brew House",
    "nearby_place2_url": "https://foursquare.com/v/bjs-brew-house/4bfe6fb2f61dc9b6fe65a0de",
    "nearby_place3_name": "Mck's Tavern",
    "nearby_place3_url": "https://foursquare.com/v/mcks-tavern/4b4d2c3cf964a5204bcd26e3",
    "hotel1_name": "Ocean Deck",
    "hotel1_url": "https://foursquare.com/v/ocean-deck/4b058690f964a5200c6622e3",
    "hotel2_name": "Tia Coris Tacos",
    "hotel2_url": "https://foursquare.com/v/tia-coris-tacos/4bddc8d8ffdec928c768e6a1",
    "hotel3_name": null,
    "hotel3_url": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Daytona_Beach,_Florida",
    "wikitravel_url": "http://wikitravel.org/en/Daytona_Beach",
    "wiki_text": "Daytona Beach is a city in Volusia County, Florida, United States. The city lies about 51 miles (82.1 km) northeast of Orlando, 86 miles (138.4 km) southeast of Jacksonville, and 242 miles (389.5 km) northwest of Miami.",
    "best_season": ["nov","dec","jan"]
},

{	"id": "3226114142",
    "location": "Arches National Park, Utah",
    "source": "reddit",
    "source_link": "http://www.reddit.com/r/EarthPorn/comments/1q9g1q/sunrise_over_turret_arch_through_the_north_window/",
    "image_link": "http://farm6.staticflickr.com/5526/10764082226_c9309bc3d9_b.jpg",
    "lat_long": ["38.6833","109.5667"],
    "weather_link": "http://weather.yahoo.com/united-states/utah/arches-national-park-23505167/#toggle",
    "weather_current_type": "fair",
    "weather_current_now": 7,
    "weather_today_high": 18,
    "weather_today_low": 1,
    "nearby_place1_name": "Arches National Park",
    "nearby_place1_url": "https://foursquare.com/v/arches-national-park/4bb77963cf2fc9b61d3d9e02",
    "nearby_place2_name": "Eklecticafe",
    "nearby_place2_url": "https://foursquare.com/v/eklecticafe/4b3a236df964a520856125e3",
    "nearby_place3_name": "Moab Brewery",
    "nearby_place3_url": "https://foursquare.com/v/moab-brewery/4b36b72ff964a5202f3b25e3",
    "hotel1_name": "Milts stop eat",
    "hotel1_url": "https://foursquare.com/v/milts-stop--eat/4b9ffe3ef964a520a05037e3",
    "hotel2_name": "Zax",
    "hotel2_url": "https://foursquare.com/v/zax/4b382b7bf964a520724c25e3",
    "hotel3_name": "Love Muffin Cafe",
    "hotel3_url": "https://foursquare.com/v/love-muffin-cafe/4bd4541377b29c7491659282",
    "wikipedia_url": "https://en.wikipedia.org/wiki/Arches_National_Park",
    "wikitravel_url": "http://wikitravel.org/en/Arches_National_Park",
    "wiki_text": "Arches National Park is a United States National Park that is in Utah's Canyon Country near the town of Moab. It is home to the world's greatest concentration of natural arches, including the famous Delicate Arch that was seen all over the world during the 2002 Salt Lake City Winter Olympics.",
    "best_season": ["nov","dec","jan"]
},

{	"id": "3226114143",
    "location": "Starved Rock State Park, IL",
    "source": "reddit",
    "source_link": "http://www.reddit.com/r/EarthPorn/comments/1q6tvw/drove_6_hours_hiked_5_miles_and_waded_through_40/",
    "image_link": "http://i.imgur.com/D7XICMZ.jpg",
    "lat_long": ["41.3214", "88.9903"],
    "weather_link": "http://weather.yahoo.com/united-states/maryland/rocks-state-park-55839638/#toggle",
    "weather_current_type": "partly cloudly",
    "weather_current_now": 9,
    "weather_today_high": 11,
    "weather_today_low": 4,
    "nearby_place1_name": "Starved Rock State Park",
    "nearby_place1_url": "https://foursquare.com/v/starved-rock-state-park/4b522729f964a520e06b27e3",
    "nearby_place2_name": null,
    "nearby_place2_url": null,
    "nearby_place3_name": null,
    "nearby_place3_url": null,
    "hotel1_name": "Fairfield Inn & Suites Marriott",
    "hotel1_url": "https://foursquare.com/v/fairfield-inn--suites-marriott/4de0282152b1c1b3ce2bac28",
    "hotel2_name": "Best Western Oglesby Inn",
    "hotel2_url": "https://foursquare.com/v/best-western-oglesby-inn/4bf85fdfb182c9b69d67775a",
    "hotel3_name": null,
    "hotel3_url": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Starved_Rock_State_Park",
    "wikitravel_url": "http://wikitravel.org/en/Starved_Rock_State_Park",
    "wiki_text": "Starved Rock State Park is a state park in the U.S. state of Illinois, characterized by the many canyons within its 2,630 acres (1,064 ha). Located just southeast of the village of Utica, in Deer Park Township, LaSalle County, Illinois, along the south bank of the Illinois River, the park hosts over two million visitors annually",
    "best_season": ["nov","dec","jan"]
},

{	"id": "3226114144",
    "location": "Prague, Bohemia, Czech Republic",
    "source": "reddit",
    "source_link": "http://www.reddit.com/r/CityPorn/comments/17vavb/prague_cityscape_1920x1200/",
    "image_link": "http://i.imgur.com/xDGOSg4.jpg",
    "lat_long": ["50.0833","14.4167"],
    "weather_link": "http://weather.yahoo.com/czech-republic/hlavni-mesto-praha/prague-796597/#toggle",
    "weather_current_type": "mostly cloudly",
    "weather_current_now": 10,
    "weather_today_high": 11,
    "weather_today_low": 3,
    "nearby_place1_name": "Café Palanda",
    "nearby_place1_url": "https://foursquare.com/v/caf%C3%A9-palanda/4b7560def964a5202a092ee3",
    "nearby_place2_name": "Lokál",
    "nearby_place2_url": "https://foursquare.com/v/lok%C3%A1l/4af5389cf964a5209af821e3",
    "nearby_place3_name": "SaSaZu Prague",
    "nearby_place3_url": "https://foursquare.com/v/sasazu-prague/4af3fe7cf964a520c7ef21e3",
    "hotel1_name": "Hilton Prague",
    "hotel1_url": "https://foursquare.com/v/hilton-prague/4adcda9af964a5201e4c21e3",
    "hotel2_name": "Corinthia Hotel Prague",
    "hotel2_url": "https://foursquare.com/v/corinthia-hotel-prague-praha/4adcda9af964a520434c21e3",
    "hotel3_name": "Hotel Joseph",
    "hotel3_url": "https://foursquare.com/v/hotel-josef-prague-czech-republic/4adcda9bf964a5206d4c21e3",
    "wikipedia_url": "https://en.wikipedia.org/wiki/Prague",
    "wikitravel_url": "http://wikitravel.org/en/Prague",
    "wiki_text": "Prague is the capital city and largest city of the Czech Republic. It is one of the largest cities of Central Europe and has served as the capital of the historic region of Bohemia for centuries.",
    "best_season": ["jun","jul","aug"]
},

{	"id": "3226114145",
    "location": "Navagio Beach, Zakynthos, Greece",
    "source": "reddit",
    "source_link": "http://www.reddit.com/r/EarthPorn/comments/1q711o/navagio_beach_zakynthos_greece_1920_x_1200/",
    "image_link": "http://i.imgur.com/AUhVcQZ.jpg",
    "lat_long": ["37.8000","20.7500"],
    "weather_link": "http://weather.yahoo.com/greece/nisia-ionioy/zakinthos-airport-12513332/#toggle",
    "weather_current_type": "mostly cloudly",
    "weather_current_now": 20,
    "weather_today_high": 21,
    "weather_today_low": 8,
    "nearby_place1_name": "Base",
    "nearby_place1_url": "https://foursquare.com/v/base/4c61aecb69a1c9b63ade36a4",
    "nearby_place2_name": "Movida",
    "nearby_place2_url": "https://foursquare.com/v/movida/4c65c19fc2ead13a16f2b180",
    "nearby_place3_name": "Avant Grade",
    "nearby_place3_url": "https://foursquare.com/v/avant-garde/4f86ad40e4b0270511075671",
    "hotel1_name": "Lobby Cafe",
    "hotel1_url": "https://foursquare.com/v/lobby-cafe/4d17834f302da1cd2e52bc93",
    "hotel2_name": "locos",
    "hotel2_url": "https://foursquare.com/v/locos/4d2ef6175055a35d653397ca",
    "hotel3_name": null,
    "hotel3_url": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Zakynthos",
    "wikitravel_url": "http://wikitravel.org/en/Zakynthos",
    "wiki_text": "Zakynthos (Greek: Ζάκυνθος), also called Zante (its Italian name), is the third largest island in the Ionian Sea, located off the west coast of Greece. The island is named after Zacynthos, son of legendary Arcadian chief Dardanos.",
    "best_season": ["jun","jul","aug"]
},

{	"id": "3226114146",
    "location": "Yosemite National Park California",
    "source": "reddit",
    "source_link": "http://www.reddit.com/r/EarthPorn/comments/1q8jot/yosemite_national_park_california_oc_4273x2987/",
    "image_link": "http://farm6.staticflickr.com/5494/10748130644_51cd67fd85_b.jpg",
    "lat_long": ["37.8499","119.5677"],
    "weather_link": "http://weather.yahoo.com/united-states/california/yosemite-national-park-55813396/#toggle",
    "weather_current_type": "mostly cloudly",
    "weather_current_now": 15,
    "weather_today_high": 25,
    "weather_today_low": 3,
    "nearby_place1_name": "Ansel Adams Gallery",
    "nearby_place1_url": "https://foursquare.com/v/ansel-adams-gallery/4ae28bb3f964a520f08e21e3",
    "nearby_place2_name": "Yosemite National Park",
    "nearby_place2_url": "https://foursquare.com/v/yosemite-national-park/4ba3d06ef964a520706238e3",
    "nearby_place3_name": null,
    "nearby_place3_url": null,
    "hotel1_name": "Degnans Deli",
    "hotel1_url": "https://foursquare.com/v/degnans-deli/4b12b62ef964a520a18c23e3",
    "hotel2_name": "Village Grill",
    "hotel2_url": "https://foursquare.com/v/village-grill/4deac399e4cdc079f48db18d",
    "hotel3_name": null,
    "hotel3_url": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Yosemite_National_Park",
    "wikitravel_url": "http://wikitravel.org/en/Yosemite_National_Park",
    "wiki_text": "Yosemite National Park  is a United States National Park and a UNESCO World Heritage Site located in the Sierra Nevada mountains in east-central California. Yosemite is internationally recognized for its spectacular granite cliffs, waterfalls, clear streams, giant sequoia groves, and biological diversity.",
    "best_season": ["jun","jul","aug"]
},

{	"id": "3226114130",
    "location": "Great Smoky Mountains",
    "source": "reddit",
    "source_link": "http://www.reddit.com/r/EarthPorn/comments/1q7xqz/great_smoky_mountains_1400_x_933_oc/",
    "image_link": "http://farm6.staticflickr.com/5495/10750221524_77190a52ed_o.jpg",
    "lat_long": ["41.3214N", "88.9903W"],
    "weather_link": "http://weather.yahoo.com/united-states/maryland/rocks-state-park-55839638/#toggle",
    "weather_current_type": "partly cloudly",
    "weather_current_now": 9,
    "weather_today_high": 11,
    "weather_today_low": 4,
    "nearby_place1_name": "Smoky Mountain ",
    "nearby_place1_url": "https://foursquare.com/v/plage-de-mahdia/4e2aec2f636553b25b66136c",
    "nearby_place2_name": "smoky Resorts",
    "nearby_place2_url": "null",
    "nearby_place3_name": "null",
    "nearby_place3_url": "null",
    "hotel1_name": "Cafe El-Asfour",
    "hotel1_url": "https://foursquare.com/v/cafe-elasfour/4e5e8d977d8b67dc8ff5da03",
    "hotel2_name": "Café el M'dina",
    "hotel2_url": "https://foursquare.com/v/caf%C3%A9-el-mdina/4e2812d7b3ad3ecf934f48ae",
    "hotel3_name": null,
    "hotel3_url": null,
    "wikipedia_url": "http://en.wikipedia.org/wiki/Great_Smoky_Mountains",
    "wikitravel_url": "http://en.wikipedia.org/wiki/Great_Smoky_Mountains",
    "wiki_text": "Great Smoky Mountains National Park is a United States National Park and UNESCO World Heritage Site that straddles the ridgeline of the Great Smoky Mountains, part of the Blue Ridge Mountains, which ..",
    "best_season": ["nov","dec","jan"]
},

{	"id": "3226114131",
    "location": "Alaska Range , Denali Park, Alaska",
    "source": "flickr.com",
    "source_link": "http://www.reddit.com/r/EarthPorn/comments/1qakdz/alaska_range_denali_park_alaska_by_jay_berkow/",
    "image_link": "http://farm6.staticflickr.com/5446/9584968216_0e6f9b6b21_b.jpg",
    "lat_long": ["64","140"],
    "weather_link": "http://weather.yahoo.com/canada/prince-edward-island/alaska-23390126/",
    "weather_current_type": "clear sky",
    "weather_current_now": 3,
    "weather_today_high": 12,
    "weather_today_low": -3,
    "nearby_place1_name": "Café Palanda",
    "nearby_place1_url": "https://foursquare.com/v/caf%C3%A9-palanda/4b7560def964a5202a092ee3",
    "nearby_place2_name": "Lokál",
    "nearby_place2_url": "https://foursquare.com/v/lok%C3%A1l/4af5389cf964a5209af821e3",
    "nearby_place3_name": "SaSaZu Prague",
    "nearby_place3_url": "https://foursquare.com/v/sasazu-prague/4af3fe7cf964a520c7ef21e3",
    "hotel1_name": "Hilton Prague",
    "hotel1_url": "https://foursquare.com/v/hilton-prague/4adcda9af964a5201e4c21e3",
    "hotel2_name": "Corinthia Hotel Prague",
    "hotel2_url": "https://foursquare.com/v/corinthia-hotel-prague-praha/4adcda9af964a520434c21e3",
    "hotel3_name": "Hotel Joseph",
    "hotel3_url": "https://foursquare.com/v/hotel-josef-prague-czech-republic/4adcda9bf964a5206d4c21e3",
    "wikipedia_url": "https://en.wikipedia.org/wiki/Prague",
    "wikitravel_url": "http://wikitravel.org/en/Prague",
    "wiki_text": "Prague is the capital city and largest city of the Czech Republic. It is one of the largest cities of Central Europe and has served as the capital of the historic region of Bohemia for centuries.",
    "best_season": ["jun","jul","aug"]
},

{ "id": "3226114132",
    "location": "Hraunfossar (lava falls) Iceland",
    "source": "i.imgur.com",
    "source_link": "http://www.reddit.com/r/EarthPorn/comments/1q6cj0/hraunfossar_lava_falls_iceland_2222_x_500/",
    "image_link": "http://i.imgur.com/jTIHIU0.jpg",
    "lat_long": ["65","18"],
    "weather_link": "http://weather.yahoo.com/iceland/reykjavik/reykjavik-20070109/",
    "weather_current_type": "rainy",
    "weather_current_now": -2,
    "weather_today_high": 2,
    "weather_today_low": -15,
    "nearby_place1_name": "Grillmarkaðurinn",
    "nearby_place1_url": "https://foursquare.com/v/grillmarka%C3%B0urinn/4d9caea548b6224b266e139f",
    "nearby_place2_name": "Lebowski Bar",
    "nearby_place2_url": "https://foursquare.com/v/lebowski-bar/4f8f2098e4b09b4d92a00414",
    "nearby_place3_name": null,
    "nearby_place3_url": null,
    "hotel1_name": "Reykjavík Roasters",
    "hotel1_url": "https://foursquare.com/v/reykjav%C3%ADk-roasters/4b0e7b9bf964a520e05723e3",
    "hotel2_name": "Kaffibarinn",
    "hotel2_url": "https://foursquare.com/v/kaffibarinn/4b2eaca7f964a520c6e424e3",
    "hotel3_name":null,
    "hotel3_url": null,
    "wikipedia_url": "http://en.wikipedia.org/wiki/Reykjavik,_Iceland",
    "wikitravel_url": "http://en.wikipedia.org/wiki/Reykjavik,_Iceland",
    "wiki_text": "Reykjavík (Icelandic pronunciation: [ˈreiːcaˌviːk] ( listen)) is the capital and largest city of Iceland. Its latitude, at 64°08' N, makes it the world's northernmost capital of a sovereign state. It is located in southwestern Iceland, on the southern shore of the Faxaflói Bay",
    "best_season": ["jun","jul","aug"]
},

{ "id": "3226114133",
    "location": "Shenandoah National Park, Virginia",
    "source": "flickr.com",
    "source_link": "http://www.reddit.com/r/EarthPorn/comments/1qap9q/old_rag_summit_fall_2013_shenandoah_national_park/",
    "image_link": "http://farm6.staticflickr.com/5529/10772833395_7abbe3f325_b.jpg",
    "lat_long": ["38","78"],
    "weather_link": "http://weather.yahoo.com/united-states/virginia/virginia-beach-2512636/",
    "weather_current_type": "partly Cloudy",
    "weather_current_now": 10,
    "weather_today_high": 13,
    "weather_today_low": 8,
    "nearby_place1_name": "The Quad",
    "nearby_place1_url": "https://foursquare.com/v/the-quad/4bb503a362fca5933c43f17e",
    "nearby_place2_name": "Car and Carriage Caravan Museum",
    "nearby_place2_url": "https://foursquare.com/v/car-and-carriage-caravan-museum/4db44a366a23c31a031409e7",
    "nearby_place3_name": null,
    "nearby_place3_url": null,
    "hotel1_name": "Artful Dodger Cafe & Cocktail Lounge",
    "hotel1_url": "https://foursquare.com/v/artful-dodger-cafe-cocktail-lounge-harrisonburg-va/4ab54aa6f964a520c77320e3",
    "hotel2_name": "Jack Brown's Beer & Burger Joint",
    "hotel2_url": "https://foursquare.com/v/jack-browns-beer--burger-joint/4b0ae48ef964a520922923e3",
    "hotel3_name":null,
    "hotel3_url": null,
    "wikipedia_url": "http://en.wikipedia.org/wiki/Shenandoah_National_Park",
    "wikitravel_url": "http://en.wikipedia.org/wiki/Shenandoah_National_Park",
    "wiki_text": "Shenandoah National Park encompasses part of the Blue Ridge Mountains in the U.S. state of Virginia. This national park is long and narrow, with the broad Shenandoah River and Valley on the west side, and the rolling hills of the Virginia Piedmont on the east. ",
    "best_season": ["jun","jul","aug"]
},

{ "id": "3226114134",
    "location": "Bryce Canyon, UT, US",
    "source": "imgur.com",
    "source_link": "http://www.reddit.com/r/EarthPorn/comments/1qafey/bryce_canyon_ut_us_1920x1080iphone_quality/",
    "image_link": "http://i.imgur.com/xAz0rJW.jpg",
    "lat_long": ["37","112"],
    "weather_link": "http://weather.yahoo.com/united-states/utah/bryce-canyon-2370940/",
    "weather_current_type": "clear sky",
    "weather_current_now": 4,
    "weather_today_high": 13,
    "weather_today_low": -1,
    "nearby_place1_name": "Bryce Canyon General Store",
    "nearby_place1_url": "https://foursquare.com/v/bryce-canyon-general-store/4fc25f3fe4b00dd50ec13314",
    "nearby_place2_name": "Bryce Canyon Lodge Resautant",
    "nearby_place2_url": "https://foursquare.com/v/bryce-canyon-lodge-resautant/4e0386f9a809d5cf4528a360",
    "nearby_place3_name": null,
    "nearby_place3_url": null,
    "hotel1_name": "Ruby's Inn Restaurant",
    "hotel1_url": "https://foursquare.com/v/rubys-inn-restaurant/4d9f7f4b5dc7f04d82127091",
    "hotel2_name": "Bryce Canyon Lodge Resautant",
    "hotel2_url": "https://foursquare.com/v/bryce-canyon-lodge-resautant/4e0386f9a809d5cf4528a360",
    "hotel3_name":null,
    "hotel3_url": null,
    "wikipedia_url": "http://en.wikipedia.org/wiki/Bryce_Canyon_City,_Utah",
    "wikitravel_url": "http://en.wikipedia.org/wiki/Bryce_Canyon_City,_Utah",
    "wiki_text": "Bryce Canyon City is a town in Garfield County, Utah, United States, adjacent to Bryce Canyon National Park. The town, formerly known as Ruby's Inn, was officially incorporated on July 23, 2007 under a controversial, short-lived state law. ",
    "best_season": ["jun","jul","aug"]
},


{ "id": "3226114148",
    "location": "Krka National Park, Croatia ",
    "source": "reddit.com",
    "source_link": "http://www.reddit.com/r/EarthPorn/comments/1qavcz/krka_national_park_croatia_2000_667oc/",
    "image_link": "http://i.imgur.com/ZxJK1TL.jpg",
    "lat_long": ["43.8019","15.9728"],
    "weather_link": "http://weather.yahoo.com/croatia/sibenska/nacionalni-park-krka-56058431/",
    "weather_current_type": "partly cloudy",
    "weather_current_now": 21,
    "weather_today_high": 18,
    "weather_today_low": 13,
    "nearby_place1_name": "Pelegrin",
    "nearby_place1_url": "https://foursquare.com/v/pelegrini/4c2a48c4c758e21e73673a3f",
    "nearby_place2_name": null,
    "nearby_place2_url": null,
    "nearby_place3_name": null,
    "nearby_place3_url": null,
    "hotel1_name": null,
    "hotel1_url": null,
    "hotel2_name": null,
    "hotel2_url": null,
    "hotel3_name":null,
    "hotel3_url": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Krka_National_Park",
    "wikitravel_url": "http://wikitravel.org/en/Krka_National_Park",
    "wiki_text": "Krka National Park (Croatian: Nacionalni park Krka) is one of the Croatian national parks, named after the river Krka that it encloses. It is located along the middle-lower course of the Krka River in central Dalmatia, in Šibenik-Knin county, downstream Miljevci area, and just a few kilometers northeast of the city of Šibenik. ",
    "best_season": ["jun","jul","aug"]
},

{ "id": "3226114135",
    "location": "Moraine Lake, Banff",
    "source": "ppcdn.500px.org",
    "source_link": "www.reddit.com/r/EarthPorn/comments/1qapx6/moraine_lake_banff_canada_1170x780_os_pete_piriya/",
    "image_link": "http://ppcdn.500px.org/13945537/092d14370fb15e36ab31a3fd056ba6ead158d18c/5.jpg",
    "lat_long": ["51","116"],
    "weather_link": "http://weather.yahoo.com/canada/alberta/banff-8465/",
    "weather_current_type": "clear sky",
    "weather_current_now": -8,
    "weather_today_high": -5,
    "weather_today_low": -14,
    "nearby_place1_name": "Evelyn's Coffee Bar",
    "nearby_place1_url": "https://foursquare.com/v/evelyns-coffee-bar-banff-alberta/4b661f25f964a520db142be3",
    "nearby_place2_name": "Grizzly House",
    "nearby_place2_url": "https://foursquare.com/v/grizzly-house/4b8f0280f964a520474433e3",
    "nearby_place3_name": null,
    "nearby_place3_url": null,
    "hotel1_name": "The Bison Restaurant & Lounge",
    "hotel1_url": "https://foursquare.com/v/the-bison-restaurant--lounge/4b5671d8f964a520a81028e3",
    "hotel2_name": "Earls Restaurant",
    "hotel2_url": "https://foursquare.com/v/earls-restaurant/4b6b2535f964a520b0f52be3",
    "hotel3_name":null,
    "hotel3_url": null,
    "wikipedia_url": "http://en.wikipedia.org/wiki/Moraine_Lake",
    "wikitravel_url": "http://en.wikipedia.org/wiki/Moraine_Lake",
    "wiki_text": "Moraine Lake is a glacially-fed lake in Banff National Park, 14 kilometres (8.7 mi) outside the Village of Lake Louise, Alberta, Canada. It is situated in the Valley of the Ten Peaks, at an elevation of approximately 6,183 feet (1,885 m). The lake has a surface area of .5 square kilometres (0.19 sq mi).",
    "best_season": ["jun","jul","aug"]
}

]
}
