{"pages" :[

{	"id": "1234567890",
    "location": "Starved Rock State Park, IL",
    "source": "reddit",
    "source_link": "http://www.reddit.com/r/EarthPorn/comments/1q6tvw/drove_6_hours_hiked_5_miles_and_waded_through_40/",
    "image_link": "http://i.imgur.com/D7XICMZ.jpg",
    "lat_long": ["41.3214", "88.9903"],
    "weather_link": "http://weather.yahoo.com/united-states/maryland/rocks-state-park-55839638/#toggle",
    "weather_current_type": "partly cloudly",
    "weather_current_now": 9,
    "weather_today_high": 11,
    "weather_today_low": 4,
    "nearby_place1_name": "Starved Rock State Park",
    "nearby_place1_url": "https://foursquare.com/v/starved-rock-state-park/4b522729f964a520e06b27e3",
    "nearby_place2_name": null,
    "nearby_place2_url": null,
    "nearby_place3_name": null,
    "nearby_place3_url": null,
    "hotel1_name": "Fairfield Inn & Suites Marriott",
    "hotel1_url": "https://foursquare.com/v/fairfield-inn--suites-marriott/4de0282152b1c1b3ce2bac28",
    "hotel2_name": "Best Western Oglesby Inn",
    "hotel2_url": "https://foursquare.com/v/best-western-oglesby-inn/4bf85fdfb182c9b69d67775a",
    "hotel3_name": null,
    "hotel3_url": null,
    "wikipedia_url": "https://en.wikipedia.org/wiki/Starved_Rock_State_Park",
    "wikitravel_url": "http://wikitravel.org/en/Starved_Rock_State_Park",
    "wiki_text": "Starved Rock State Park is a state park in the U.S. state of Illinois, characterized by the many canyons within its 2,630 acres (1,064 ha). Located just southeast of the village of Utica, in Deer Park Township, LaSalle County, Illinois, along the south bank of the Illinois River, the park hosts over two million visitors annually",
    "best_season": ["nov","dec","jan"]
},

{	"id": "1234567891",
    "location": "Prague, Bohemia, Czech Republic",
    "source": "reddit",
    "source_link": "http://www.reddit.com/r/CityPorn/comments/17vavb/prague_cityscape_1920x1200/",
    "image_link": "http://i.imgur.com/xDGOSg4.jpg",
    "lat_long": ["50.0833","14.4167"],
    "weather_link": "http://weather.yahoo.com/czech-republic/hlavni-mesto-praha/prague-796597/#toggle",
    "weather_current_type": "mostly cloudly",
    "weather_current_now": 10,
    "weather_today_high": 11,
    "weather_today_low": 3,
    "nearby_place1_name": "Café Palanda",
    "nearby_place1_url": "https://foursquare.com/v/caf%C3%A9-palanda/4b7560def964a5202a092ee3",
    "nearby_place2_name": "Lokál",
    "nearby_place2_url": "https://foursquare.com/v/lok%C3%A1l/4af5389cf964a5209af821e3",
    "nearby_place3_name": "SaSaZu Prague",
    "nearby_place3_url": "https://foursquare.com/v/sasazu-prague/4af3fe7cf964a520c7ef21e3",
    "hotel1_name": "Hilton Prague",
    "hotel1_url": "https://foursquare.com/v/hilton-prague/4adcda9af964a5201e4c21e3",
    "hotel2_name": "Corinthia Hotel Prague",
    "hotel2_url": "https://foursquare.com/v/corinthia-hotel-prague-praha/4adcda9af964a520434c21e3",
    "hotel3_name": "Hotel Joseph",
    "hotel3_url": "https://foursquare.com/v/hotel-josef-prague-czech-republic/4adcda9bf964a5206d4c21e3",
    "wikipedia_url": "https://en.wikipedia.org/wiki/Prague",
    "wikitravel_url": "http://wikitravel.org/en/Prague",
    "wiki_text": "Prague is the capital city and largest city of the Czech Republic. It is one of the largest cities of Central Europe and has served as the capital of the historic region of Bohemia for centuries.",
    "best_season": ["jun","jul","aug"]
}

]
}
